# Generated by Django 5.1.5 on 2026-04-13 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usual_country', models.CharField(blank=True, max_length=64)),
                ('usual_city', models.CharField(blank=True, max_length=64)),
                ('usual_timezone', models.CharField(blank=True, max_length=64)),
                ('usual_language', models.CharField(blank=True, max_length=64)),
                ('typical_login_hour', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('typical_login_weekday', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_provider', models.CharField(blank=True, max_length=128)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrustedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint_hash', models.CharField(max_length=128)),
                ('user_agent', models.TextField(blank=True)),
                ('platform', models.CharField(blank=True, max_length=64)),
                ('timezone', models.CharField(blank=True, max_length=64)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'fingerprint_hash')},
            },
        ),
    ]
