# Generated by Django 5.1.5 on 2026-04-13 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('success', 'success'), ('success_mfa', 'success_mfa'), ('pending_mfa', 'pending_mfa'), ('failed', 'failed'), ('blocked', 'blocked')], max_length=16)),
                ('decision', models.CharField(choices=[('allow', 'allow'), ('require_mfa', 'require_mfa'), ('block', 'block')], default='allow', max_length=16)),
                ('risk_level', models.CharField(blank=True, max_length=16)),
                ('risk_score', models.FloatField(default=0.0)),
                ('factor_scores', models.JSONField(blank=True, default=dict)),
                ('explanation', models.JSONField(blank=True, default=list)),
                ('request_context', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, max_length=128)),
                ('is_vpn_proxy', models.BooleanField(default=False)),
                ('failure_reason', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MFAChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('login_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_challenges', to='authentication.loginattempt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
